<a href="https://colab.research.google.com/github/haripriyaa334-pixel/Decode-labs-internship-/blob/main/Decodeproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from google.colab import files
uploaded = files.upload()

Saving Dataset for Data Analytics.xlsx to Dataset for Data Analytics.xlsx

In [6]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive

In [10]:
import pandas as pd

In [11]:
data= pd.read_excel("Dataset for Data Analytics.xlsx")

In [12]:
data.drop_duplicates(inplace=True)
data.dropna(inplace=True)
data.fillna("null",inplace=True)
data.columns=data.columns.str.lower()

In [13]:
print(type(data))
print(data.shape if hasattr(data, 'shape') else "No shape")
print(data[:5] if not hasattr(data, 'head') else data.head())

<class 'pandas.core.frame.DataFrame'>
(891, 14)
     orderid       date customerid  product  quantity  unitprice  \
0  ORD200000 2023-01-04     C72649  Monitor         5     570.62
1  ORD200001 2024-08-23     C75739    Phone         2     151.35
2  ORD200002 2024-02-27     C81728   Tablet         5     550.68
3  ORD200003 2023-10-15     C33540    Chair         1     273.19
4  ORD200004 2025-05-08     C81840  Printer         4     626.01

  shippingaddress paymentmethod orderstatus trackingnumber  itemsincart  \
0     928 Main St    Debit Card     Shipped    TRK37947903            7
1     823 Main St        Online     Shipped    TRK91186779            3
2     512 Main St   Credit Card   Cancelled    TRK42903982            8
3     275 Main St    Debit Card    Returned    TRK62788070            5
4     668 Main St        Online   Delivered    TRK29241424            8

  couponcode referralsource  totalprice
0     SAVE10      Instagram     2853.10
1     SAVE10       Referral      302.70
2   FREESHIP          Email     2753.40
3     SAVE10       Facebook      273.19
4     SAVE10          Email     2504.04

In [14]:
data['date']=pd.to_datetime(data['date'])

In [15]:
data.head()

,orderid,date,customerid,product,quantity,unitprice,shippingaddress,paymentmethod,orderstatus,trackingnumber,itemsincart,couponcode,referralsource,totalprice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [16]:
data.tail()

,orderid,date,customerid,product,quantity,unitprice,shippingaddress,paymentmethod,orderstatus,trackingnumber,itemsincart,couponcode,referralsource,totalprice
1194,ORD201194,2023-11-19,C29885,Printer,3,189.44,725 Main St,Cash,Pending,TRK62067865,4,FREESHIP,Email,568.32
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [17]:
data.describe()

,date,quantity,unitprice,itemsincart,totalprice
count,891,891.000000,891.000000,891.000000,891.000000
mean,2024-03-25 05:34:32.727272704,2.911336,360.596835,5.459035,1057.643715
min,2023-01-01 00:00:00,1.000000,11.390000,1.000000,11.390000
25%,2023-08-16 00:00:00,2.000000,189.345000,4.000000,415.785000
50%,2024-03-23 00:00:00,3.000000,371.290000,5.000000,819.500000
75%,2024-11-10 00:00:00,4.000000,526.445000,7.000000,1581.135000
max,2025-06-30 00:00:00,5.000000,699.930000,10.000000,3456.400000
std,NaN,1.414212,196.752386,2.277209,822.703899

In [18]:
num_cols = data.select_dtypes(include='number').columns
data[num_cols] = data[num_cols].round(0)

In [19]:
data.head()

,orderid,date,customerid,product,quantity,unitprice,shippingaddress,paymentmethod,orderstatus,trackingnumber,itemsincart,couponcode,referralsource,totalprice
0,ORD200000,2023-01-04,C72649,Monitor,5,571.0,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.0
1,ORD200001,2024-08-23,C75739,Phone,2,151.0,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,303.0
2,ORD200002,2024-02-27,C81728,Tablet,5,551.0,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.0
3,ORD200003,2023-10-15,C33540,Chair,1,273.0,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.0
4,ORD200004,2025-05-08,C81840,Printer,4,626.0,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.0

In [20]:
data.to_excel("cleanedD.xlsx",index=False)

In [21]:
files.download("cleanedD.xlsx")